# Makefile.in generated by automake 1.10.1 from Makefile.am.
# src/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Source Makefile.am
#
# Copyright (c) 2008 Free Software Foundation, Inc.
# Copyright (c) 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004 Sandro Sigala.
# Copyright (c) 2003, 2004, 2005, 2006, 2007, 2008 Reuben Thomas.
# Copyright (c) 2004 David Capello.
#
# This file is part of GNU Zile.
#
# GNU Zile is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# GNU Zile is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Zile; see the file COPYING.  If not, write to the
# Free Software Foundation, Fifth Floor, 51 Franklin Street, Boston,
# MA 02111-1301, USA.


pkgdatadir = $(datadir)/zile
pkglibdir = $(libdir)/zile
pkgincludedir = $(includedir)/zile
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
TESTS = astr$(EXEEXT)
check_PROGRAMS = astr$(EXEEXT)
bin_PROGRAMS = zile$(EXEEXT)
subdir = src
DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/alloca.m4 \
	$(top_srcdir)/m4/canonicalize-lgpl.m4 \
	$(top_srcdir)/m4/chdir-long.m4 $(top_srcdir)/m4/chown.m4 \
	$(top_srcdir)/m4/codeset.m4 $(top_srcdir)/m4/d-ino.m4 \
	$(top_srcdir)/m4/dirfd.m4 $(top_srcdir)/m4/dirname.m4 \
	$(top_srcdir)/m4/dos.m4 $(top_srcdir)/m4/double-slash-root.m4 \
	$(top_srcdir)/m4/dup2.m4 $(top_srcdir)/m4/eealloc.m4 \
	$(top_srcdir)/m4/eoverflow.m4 $(top_srcdir)/m4/error.m4 \
	$(top_srcdir)/m4/euidaccess.m4 $(top_srcdir)/m4/exitfail.m4 \
	$(top_srcdir)/m4/extensions.m4 $(top_srcdir)/m4/fchdir.m4 \
	$(top_srcdir)/m4/fcntl-safer.m4 $(top_srcdir)/m4/fcntl_h.m4 \
	$(top_srcdir)/m4/float_h.m4 \
	$(top_srcdir)/m4/getcwd-abort-bug.m4 \
	$(top_srcdir)/m4/getcwd-path-max.m4 $(top_srcdir)/m4/getcwd.m4 \
	$(top_srcdir)/m4/getopt.m4 $(top_srcdir)/m4/gl_list.m4 \
	$(top_srcdir)/m4/glibc21.m4 $(top_srcdir)/m4/gnulib-common.m4 \
	$(top_srcdir)/m4/gnulib-comp.m4 \
	$(top_srcdir)/m4/group-member.m4 $(top_srcdir)/m4/hash.m4 \
	$(top_srcdir)/m4/include_next.m4 $(top_srcdir)/m4/inline.m4 \
	$(top_srcdir)/m4/intmax_t.m4 $(top_srcdir)/m4/inttypes_h.m4 \
	$(top_srcdir)/m4/lchown.m4 $(top_srcdir)/m4/localcharset.m4 \
	$(top_srcdir)/m4/longlong.m4 $(top_srcdir)/m4/lstat.m4 \
	$(top_srcdir)/m4/malloc.m4 $(top_srcdir)/m4/malloca.m4 \
	$(top_srcdir)/m4/mbstate_t.m4 $(top_srcdir)/m4/mempcpy.m4 \
	$(top_srcdir)/m4/memrchr.m4 $(top_srcdir)/m4/minmax.m4 \
	$(top_srcdir)/m4/onceonly.m4 $(top_srcdir)/m4/open.m4 \
	$(top_srcdir)/m4/openat.m4 $(top_srcdir)/m4/pathmax.m4 \
	$(top_srcdir)/m4/readlink.m4 $(top_srcdir)/m4/regex.m4 \
	$(top_srcdir)/m4/save-cwd.m4 $(top_srcdir)/m4/size_max.m4 \
	$(top_srcdir)/m4/ssize_t.m4 $(top_srcdir)/m4/stdarg.m4 \
	$(top_srcdir)/m4/stdbool.m4 $(top_srcdir)/m4/stdint.m4 \
	$(top_srcdir)/m4/stdint_h.m4 $(top_srcdir)/m4/stdio_h.m4 \
	$(top_srcdir)/m4/stdlib_h.m4 $(top_srcdir)/m4/strdup.m4 \
	$(top_srcdir)/m4/strerror.m4 $(top_srcdir)/m4/string_h.m4 \
	$(top_srcdir)/m4/strndup.m4 $(top_srcdir)/m4/strnlen.m4 \
	$(top_srcdir)/m4/sys_stat_h.m4 \
	$(top_srcdir)/m4/unistd-safer.m4 $(top_srcdir)/m4/unistd_h.m4 \
	$(top_srcdir)/m4/vasnprintf.m4 $(top_srcdir)/m4/vasprintf.m4 \
	$(top_srcdir)/m4/wchar.m4 $(top_srcdir)/m4/wchar_t.m4 \
	$(top_srcdir)/m4/wctype.m4 $(top_srcdir)/m4/wint_t.m4 \
	$(top_srcdir)/m4/xalloc.m4 $(top_srcdir)/m4/xgetcwd.m4 \
	$(top_srcdir)/m4/xsize.m4 $(top_srcdir)/m4/xstrndup.m4 \
	$(top_srcdir)/acinclude.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS)
astr_SOURCES = astr.c
astr_OBJECTS = astr-astr.$(OBJEXT)
am__DEPENDENCIES_1 =
am__DEPENDENCIES_2 = $(top_builddir)/lib/libgnu.a \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1)
astr_DEPENDENCIES = xalloc.o $(am__DEPENDENCIES_2)
am_zile_OBJECTS = astr.$(OBJEXT) xalloc.$(OBJEXT) eval.$(OBJEXT) \
	lists.$(OBJEXT) lisp.$(OBJEXT) basic.$(OBJEXT) bind.$(OBJEXT) \
	buffer.$(OBJEXT) completion.$(OBJEXT) editfns.$(OBJEXT) \
	file.$(OBJEXT) funcs.$(OBJEXT) glue.$(OBJEXT) help.$(OBJEXT) \
	history.$(OBJEXT) keys.$(OBJEXT) killring.$(OBJEXT) \
	line.$(OBJEXT) macro.$(OBJEXT) main.$(OBJEXT) marker.$(OBJEXT) \
	minibuf.$(OBJEXT) point.$(OBJEXT) redisplay.$(OBJEXT) \
	registers.$(OBJEXT) search.$(OBJEXT) undo.$(OBJEXT) \
	variables.$(OBJEXT) window.$(OBJEXT) term_minibuf.$(OBJEXT) \
	term_redisplay.$(OBJEXT) term_ncurses.$(OBJEXT)
zile_OBJECTS = $(am_zile_OBJECTS)
zile_DEPENDENCIES = $(am__DEPENDENCIES_2) $(LIBOBJS)
DEFAULT_INCLUDES = -I. -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = astr.c $(zile_SOURCES)
DIST_SOURCES = astr.c $(zile_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/guillaume/zile/missing --run aclocal-1.10
ALLOCA = 
ALLOCA_H = alloca.h
AMTAR = ${SHELL} /home/guillaume/zile/missing --run tar
AUTOCONF = ${SHELL} /home/guillaume/zile/missing --run autoconf
AUTOHEADER = ${SHELL} /home/guillaume/zile/missing --run autoheader
AUTOMAKE = ${SHELL} /home/guillaume/zile/missing --run automake-1.10
AWK = gawk
BITSIZEOF_PTRDIFF_T = 
BITSIZEOF_SIG_ATOMIC_T = 
BITSIZEOF_SIZE_T = 
BITSIZEOF_WCHAR_T = 
BITSIZEOF_WINT_T = 
CC = gcc -std=gnu99
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 -Wall -W -Wmissing-prototypes -Wstrict-prototypes -pedantic -D_FORTIFY_SOURCE=2
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DIRENT_H = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EOVERFLOW = 
EXEEXT = 
FCNTL_H = fcntl.h
FLOAT_H = 
GETOPT_H = 
GLIBC21 = yes
GNULIB_CALLOC_POSIX = 0
GNULIB_CHOWN = 1
GNULIB_DUP2 = 1
GNULIB_ENVIRON = 0
GNULIB_FCHDIR = 1
GNULIB_FFLUSH = 0
GNULIB_FOPEN = 0
GNULIB_FPRINTF_POSIX = 0
GNULIB_FREOPEN = 0
GNULIB_FSEEK = 0
GNULIB_FSEEKO = 0
GNULIB_FTELL = 0
GNULIB_FTELLO = 0
GNULIB_FTRUNCATE = 0
GNULIB_GETCWD = 1
GNULIB_GETDELIM = 0
GNULIB_GETLINE = 0
GNULIB_GETLOGIN_R = 0
GNULIB_GETPAGESIZE = 0
GNULIB_GETSUBOPT = 0
GNULIB_LCHOWN = 1
GNULIB_LSEEK = 0
GNULIB_MALLOC_POSIX = 1
GNULIB_MBSCASECMP = 0
GNULIB_MBSCASESTR = 0
GNULIB_MBSCHR = 0
GNULIB_MBSCSPN = 0
GNULIB_MBSLEN = 0
GNULIB_MBSNCASECMP = 0
GNULIB_MBSNLEN = 0
GNULIB_MBSPBRK = 0
GNULIB_MBSPCASECMP = 0
GNULIB_MBSRCHR = 0
GNULIB_MBSSEP = 0
GNULIB_MBSSPN = 0
GNULIB_MBSSTR = 0
GNULIB_MBSTOK_R = 0
GNULIB_MEMMEM = 0
GNULIB_MEMPCPY = 1
GNULIB_MEMRCHR = 1
GNULIB_MKDTEMP = 0
GNULIB_MKSTEMP = 0
GNULIB_OBSTACK_PRINTF = 0
GNULIB_OBSTACK_PRINTF_POSIX = 0
GNULIB_OPEN = 1
GNULIB_PRINTF_POSIX = 0
GNULIB_PUTENV = 0
GNULIB_RAWMEMCHR = 0
GNULIB_READLINK = 1
GNULIB_REALLOC_POSIX = 0
GNULIB_RPMATCH = 0
GNULIB_SETENV = 0
GNULIB_SLEEP = 0
GNULIB_SNPRINTF = 0
GNULIB_SPRINTF_POSIX = 0
GNULIB_STPCPY = 0
GNULIB_STPNCPY = 0
GNULIB_STRCASESTR = 0
GNULIB_STRCHRNUL = 0
GNULIB_STRDUP = 1
GNULIB_STRERROR = 1
GNULIB_STRNDUP = 1
GNULIB_STRNLEN = 1
GNULIB_STRPBRK = 0
GNULIB_STRSEP = 0
GNULIB_STRSIGNAL = 0
GNULIB_STRSTR = 0
GNULIB_STRTOD = 0
GNULIB_STRTOK_R = 0
GNULIB_UNSETENV = 0
GNULIB_VASPRINTF = 1
GNULIB_VFPRINTF_POSIX = 0
GNULIB_VPRINTF_POSIX = 0
GNULIB_VSNPRINTF = 0
GNULIB_VSPRINTF_POSIX = 0
GNULIB_WCWIDTH = 0
GREP = /bin/grep
HAVE_CALLOC_POSIX = 1
HAVE_DECL_ENVIRON = 1
HAVE_DECL_GETDELIM = 1
HAVE_DECL_GETLINE = 1
HAVE_DECL_GETLOGIN_R = 1
HAVE_DECL_MEMMEM = 1
HAVE_DECL_MEMRCHR = 1
HAVE_DECL_OBSTACK_PRINTF = 1
HAVE_DECL_SNPRINTF = 1
HAVE_DECL_STRDUP = 1
HAVE_DECL_STRERROR = 1
HAVE_DECL_STRNDUP = 1
HAVE_DECL_STRNLEN = 1
HAVE_DECL_STRSIGNAL = 1
HAVE_DECL_STRTOK_R = 1
HAVE_DECL_VSNPRINTF = 1
HAVE_DECL_WCWIDTH = 1
HAVE_DUP2 = 1
HAVE_FSEEKO = 1
HAVE_FTELLO = 1
HAVE_FTRUNCATE = 1
HAVE_GETPAGESIZE = 1
HAVE_GETSUBOPT = 1
HAVE_INTTYPES_H = 1
HAVE_ISWCNTRL = 1
HAVE_LONG_LONG_INT = 1
HAVE_LSTAT = 1
HAVE_MALLOC_POSIX = 1
HAVE_MEMPCPY = 1
HAVE_MKDTEMP = 1
HAVE_OS_H = 0
HAVE_RAWMEMCHR = 1
HAVE_READLINK = 1
HAVE_REALLOC_POSIX = 1
HAVE_RPMATCH = 1
HAVE_SETENV = 1
HAVE_SIGNED_SIG_ATOMIC_T = 
HAVE_SIGNED_WCHAR_T = 
HAVE_SIGNED_WINT_T = 
HAVE_SLEEP = 1
HAVE_STDINT_H = 1
HAVE_STPCPY = 1
HAVE_STPNCPY = 1
HAVE_STRCASESTR = 1
HAVE_STRCHRNUL = 1
HAVE_STRNDUP = 1
HAVE_STRPBRK = 1
HAVE_STRSEP = 1
HAVE_STRTOD = 1
HAVE_SYS_BITYPES_H = 
HAVE_SYS_INTTYPES_H = 
HAVE_SYS_PARAM_H = 0
HAVE_SYS_TYPES_H = 1
HAVE_UNISTD_H = 1
HAVE_UNSETENV = 1
HAVE_UNSIGNED_LONG_LONG_INT = 1
HAVE_VASPRINTF = 1
HAVE_WCHAR_H = 1
HAVE_WCTYPE_H = 1
HAVE_WINT_T = 1
HAVE__BOOL = 1
INCLUDE_NEXT = include_next
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBGNU_LIBDEPS = 
LIBGNU_LTLIBDEPS = 
LIBINTL = 
LIBOBJS = 
LIBS =  -lncurses
LIB_EACCESS = 
LOCALCHARSET_TESTS_ENVIRONMENT = CHARSETALIASDIR="$(top_builddir)/lib"
LTLIBINTL = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/guillaume/zile/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NEXT_DIRENT_H = 
NEXT_FCNTL_H = <fcntl.h>
NEXT_FLOAT_H = 
NEXT_STDARG_H = <stdarg.h>
NEXT_STDINT_H = <stdint.h>
NEXT_STDIO_H = <stdio.h>
NEXT_STDLIB_H = <stdlib.h>
NEXT_STRING_H = <string.h>
NEXT_SYS_STAT_H = <sys/stat.h>
NEXT_UNISTD_H = <unistd.h>
NEXT_WCHAR_H = <wchar.h>
NEXT_WCTYPE_H = <wctype.h>
OBJEXT = o
PACKAGE = zile
PACKAGE_BUGREPORT = bug-zile@gnu.org
PACKAGE_NAME = Zile
PACKAGE_STRING = Zile 2.2.62
PACKAGE_TARNAME = zile
PACKAGE_VERSION = 2.2.62
PATH_SEPARATOR = :
PTRDIFF_T_SUFFIX = 
RANLIB = ranlib
REPLACE_CHOWN = 0
REPLACE_FCHDIR = 0
REPLACE_FFLUSH = 0
REPLACE_FOPEN = 0
REPLACE_FPRINTF = 0
REPLACE_FREOPEN = 0
REPLACE_FSEEK = 0
REPLACE_FSEEKO = 0
REPLACE_FTELL = 0
REPLACE_FTELLO = 0
REPLACE_GETCWD = 1
REPLACE_GETLINE = 0
REPLACE_GETPAGESIZE = 0
REPLACE_ISWCNTRL = 0
REPLACE_LCHOWN = 0
REPLACE_LSEEK = 0
REPLACE_MEMMEM = 0
REPLACE_MKDIR = 0
REPLACE_MKSTEMP = 0
REPLACE_OBSTACK_PRINTF = 0
REPLACE_OPEN = 0
REPLACE_PRINTF = 0
REPLACE_PUTENV = 0
REPLACE_SNPRINTF = 0
REPLACE_SPRINTF = 0
REPLACE_STRCASESTR = 0
REPLACE_STRERROR = 0
REPLACE_STRSIGNAL = 0
REPLACE_STRSTR = 0
REPLACE_STRTOD = 0
REPLACE_VASPRINTF = 0
REPLACE_VFPRINTF = 0
REPLACE_VPRINTF = 0
REPLACE_VSNPRINTF = 0
REPLACE_VSPRINTF = 0
REPLACE_WCWIDTH = 0
SET_MAKE = 
SHELL = /bin/bash
SIG_ATOMIC_T_SUFFIX = 
SIZE_T_SUFFIX = 
STDARG_H = 
STDBOOL_H = 
STDINT_H = 
STRIP = 
SYS_STAT_H = sys/stat.h
VERSION = 2.2.62
VOID_UNSETENV = 0
WCHAR_H = 
WCHAR_T_SUFFIX = 
WCTYPE_H = 
WINT_T_SUFFIX = 
abs_builddir = /home/guillaume/zile/src
abs_srcdir = /home/guillaume/zile/src
abs_top_builddir = /home/guillaume/zile
abs_top_srcdir = /home/guillaume/zile
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
gl_LIBOBJS =  asnprintf.o basename.o chdir-long.o creat-safer.o dirname.o dup-safer.o exitfail.o fd-safer.o getcwd.o hash.o open-safer.o openat-proc.o pipe-safer.o printf-args.o printf-parse.o save-cwd.o stripslash.o vasnprintf.o xgetcwd.o xmalloc.o
gl_LTLIBOBJS =  asnprintf.lo basename.lo chdir-long.lo creat-safer.lo dirname.lo dup-safer.lo exitfail.lo fd-safer.lo getcwd.lo hash.lo open-safer.lo openat-proc.lo pipe-safer.lo printf-args.lo printf-parse.lo save-cwd.lo stripslash.lo vasnprintf.lo xgetcwd.lo xmalloc.lo
gltests_LIBOBJS = 
gltests_LTLIBOBJS = 
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /home/guillaume/zile/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_builddir = ..
top_srcdir = ..
SUBDIRS = testsuite
EXTRA_DIST = \
	testsuite/zile.test/zile.exp	\
	testsuite/config/unix.exp	\
	testsuite/lib/zile.exp

AM_CPPFLAGS = -I$(top_builddir)/lib -I$(top_srcdir)/lib -DPATH_DATA="\"$(pkgdatadir)\""
LDADD = $(top_builddir)/lib/libgnu.a $(LIB_EACCESS) $(LIBINTL)
astr_CPPFLAGS = -DTEST -DSRCPATH="\"$(top_srcdir)/src\"" $(AM_CPPFLAGS)
astr_LDADD = xalloc.o $(LDADD)
zile_SOURCES = \
	astr.c				\
	astr.h				\
	xalloc.c			\
	eval.c				\
	lists.c				\
	lists.h				\
	lisp.c				\
	basic.c				\
	bind.c				\
	buffer.c			\
	completion.c			\
	editfns.c			\
	extern.h			\
	zile.h				\
	file.c				\
	funcs.c				\
	glue.c				\
	help.c				\
	history.c			\
	keys.c				\
	killring.c			\
	line.c				\
	macro.c				\
	main.c				\
	marker.c			\
	minibuf.c			\
	point.c				\
	redisplay.c			\
	registers.c			\
	search.c			\
	tbl_funcs.h			\
	tbl_vars.h			\
	undo.c				\
	variables.c			\
	window.c			\
	term_minibuf.c			\
	term_redisplay.c		\
	term_ncurses.c

zile_LDADD = $(LDADD) $(LIBOBJS)
all: all-recursive

.SUFFIXES:
.SUFFIXES: .c .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  src/Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  src/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

installcheck-binPROGRAMS: $(bin_PROGRAMS)
	bad=0; pid=$$$$; list="$(bin_PROGRAMS)"; for p in $$list; do \
	  case ' $(AM_INSTALLCHECK_STD_OPTIONS_EXEMPT) ' in \
	   *" $$p "* | *" $(srcdir)/$$p "*) continue;; \
	  esac; \
	  f=`echo "$$p" | \
	     sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  for opt in --help --version; do \
	    if "$(DESTDIR)$(bindir)/$$f" $$opt >c$${pid}_.out \
	         2>c$${pid}_.err </dev/null \
		 && test -n "`cat c$${pid}_.out`" \
		 && test -z "`cat c$${pid}_.err`"; then :; \
	    else echo "$$f does not support $$opt" 1>&2; bad=1; fi; \
	  done; \
	done; rm -f c$${pid}_.???; exit $$bad

clean-checkPROGRAMS:
	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)
astr$(EXEEXT): $(astr_OBJECTS) $(astr_DEPENDENCIES) 
	@rm -f astr$(EXEEXT)
	$(LINK) $(astr_OBJECTS) $(astr_LDADD) $(LIBS)
zile$(EXEEXT): $(zile_OBJECTS) $(zile_DEPENDENCIES) 
	@rm -f zile$(EXEEXT)
	$(LINK) $(zile_OBJECTS) $(zile_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/astr-astr.Po
include ./$(DEPDIR)/astr.Po
include ./$(DEPDIR)/basic.Po
include ./$(DEPDIR)/bind.Po
include ./$(DEPDIR)/buffer.Po
include ./$(DEPDIR)/completion.Po
include ./$(DEPDIR)/editfns.Po
include ./$(DEPDIR)/eval.Po
include ./$(DEPDIR)/file.Po
include ./$(DEPDIR)/funcs.Po
include ./$(DEPDIR)/glue.Po
include ./$(DEPDIR)/help.Po
include ./$(DEPDIR)/history.Po
include ./$(DEPDIR)/keys.Po
include ./$(DEPDIR)/killring.Po
include ./$(DEPDIR)/line.Po
include ./$(DEPDIR)/lisp.Po
include ./$(DEPDIR)/lists.Po
include ./$(DEPDIR)/macro.Po
include ./$(DEPDIR)/main.Po
include ./$(DEPDIR)/marker.Po
include ./$(DEPDIR)/minibuf.Po
include ./$(DEPDIR)/point.Po
include ./$(DEPDIR)/redisplay.Po
include ./$(DEPDIR)/registers.Po
include ./$(DEPDIR)/search.Po
include ./$(DEPDIR)/term_minibuf.Po
include ./$(DEPDIR)/term_ncurses.Po
include ./$(DEPDIR)/term_redisplay.Po
include ./$(DEPDIR)/undo.Po
include ./$(DEPDIR)/variables.Po
include ./$(DEPDIR)/window.Po
include ./$(DEPDIR)/xalloc.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

astr-astr.o: astr.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(astr_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT astr-astr.o -MD -MP -MF $(DEPDIR)/astr-astr.Tpo -c -o astr-astr.o `test -f 'astr.c' || echo '$(srcdir)/'`astr.c
	mv -f $(DEPDIR)/astr-astr.Tpo $(DEPDIR)/astr-astr.Po
#	source='astr.c' object='astr-astr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(astr_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o astr-astr.o `test -f 'astr.c' || echo '$(srcdir)/'`astr.c

astr-astr.obj: astr.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(astr_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT astr-astr.obj -MD -MP -MF $(DEPDIR)/astr-astr.Tpo -c -o astr-astr.obj `if test -f 'astr.c'; then $(CYGPATH_W) 'astr.c'; else $(CYGPATH_W) '$(srcdir)/astr.c'; fi`
	mv -f $(DEPDIR)/astr-astr.Tpo $(DEPDIR)/astr-astr.Po
#	source='astr.c' object='astr-astr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(astr_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o astr-astr.obj `if test -f 'astr.c'; then $(CYGPATH_W) 'astr.c'; else $(CYGPATH_W) '$(srcdir)/astr.c'; fi`

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonemtpy = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

check-TESTS: $(TESTS)
	@failed=0; all=0; xfail=0; xpass=0; skip=0; ws='[	 ]'; \
	srcdir=$(srcdir); export srcdir; \
	list=' $(TESTS) '; \
	if test -n "$$list"; then \
	  for tst in $$list; do \
	    if test -f ./$$tst; then dir=./; \
	    elif test -f $$tst; then dir=; \
	    else dir="$(srcdir)/"; fi; \
	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *$$ws$$tst$$ws*) \
		xpass=`expr $$xpass + 1`; \
		failed=`expr $$failed + 1`; \
		echo "XPASS: $$tst"; \
	      ;; \
	      *) \
		echo "PASS: $$tst"; \
	      ;; \
	      esac; \
	    elif test $$? -ne 77; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *$$ws$$tst$$ws*) \
		xfail=`expr $$xfail + 1`; \
		echo "XFAIL: $$tst"; \
	      ;; \
	      *) \
		failed=`expr $$failed + 1`; \
		echo "FAIL: $$tst"; \
	      ;; \
	      esac; \
	    else \
	      skip=`expr $$skip + 1`; \
	      echo "SKIP: $$tst"; \
	    fi; \
	  done; \
	  if test "$$failed" -eq 0; then \
	    if test "$$xfail" -eq 0; then \
	      banner="All $$all tests passed"; \
	    else \
	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
	    fi; \
	  else \
	    if test "$$xpass" -eq 0; then \
	      banner="$$failed of $$all tests failed"; \
	    else \
	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
	    fi; \
	  fi; \
	  dashes="$$banner"; \
	  skipped=""; \
	  if test "$$skip" -ne 0; then \
	    skipped="($$skip tests were not run)"; \
	    test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
	      dashes="$$skipped"; \
	  fi; \
	  report=""; \
	  if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
	    report="Please report to $(PACKAGE_BUGREPORT)"; \
	    test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
	      dashes="$$report"; \
	  fi; \
	  dashes=`echo "$$dashes" | sed s/./=/g`; \
	  echo "$$dashes"; \
	  echo "$$banner"; \
	  test -z "$$skipped" || echo "$$skipped"; \
	  test -z "$$report" || echo "$$report"; \
	  echo "$$dashes"; \
	  test "$$failed" -eq 0; \
	else :; fi

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	    distdir=`$(am__cd) $(distdir) && pwd`; \
	    top_distdir=`$(am__cd) $(top_distdir) && pwd`; \
	    (cd $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$top_distdir" \
	        distdir="$$distdir/$$subdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-recursive
all-am: Makefile $(PROGRAMS)
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-checkPROGRAMS clean-generic \
	mostlyclean-am

distclean: distclean-recursive
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

info: info-recursive

info-am:

install-data-am:

install-dvi: install-dvi-recursive

install-exec-am: install-binPROGRAMS

install-html: install-html-recursive

install-info: install-info-recursive

install-man:

install-pdf: install-pdf-recursive

install-ps: install-ps-recursive

installcheck-am: installcheck-binPROGRAMS

maintainer-clean: maintainer-clean-recursive
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) install-am \
	install-strip

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am check check-TESTS check-am clean clean-binPROGRAMS \
	clean-checkPROGRAMS clean-generic ctags ctags-recursive \
	distclean distclean-compile distclean-generic distclean-tags \
	distdir dvi dvi-am html html-am info info-am install \
	install-am install-binPROGRAMS install-data install-data-am \
	install-dvi install-dvi-am install-exec install-exec-am \
	install-html install-html-am install-info install-info-am \
	install-man install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installcheck-binPROGRAMS installdirs installdirs-am \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags tags-recursive uninstall uninstall-am \
	uninstall-binPROGRAMS


loc:
	sloccount $(zile_SOURCES)
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
